# Generated by Django 5.0.6 on 2024-06-13 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0003_chatsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="RagDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        default="documents/default.txt", upload_to="documents/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Documents",
        ),
    ]
